name: FIRMWARE SENSOR H2

on: [push] 

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/esp-matter:latest 
    # Encendemos el caché en el entorno de Espressif
    env:
      IDF_CCACHE_ENABLE: 1
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      # --- LA MAGIA DEL CACHÉ ---
      - name: Recuperar/Guardar Caché de Compilación
        uses: actions/cache@v4
        with:
          path: .ccache
          key: ccache-matter-${{ github.sha }}
          restore-keys: |
            ccache-matter-

      - name: Compilar EXCLUSIVAMENTE para H2
        run: |
          . /opt/espressif/esp-idf/export.sh
          . /opt/espressif/esp-matter/export.sh
          idf.py set-target esp32h2
          idf.py build

      - name: Guardar el Firmware
        uses: actions/upload-artifact@v4
        with:
          name: Firmware_Sensor_H2
          path: |
            build/*.bin
            build/bootloader/*.bin
            build/partition_table/*.bin
