name: Compilar Border Router Matter

on: [push] 

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/esp-matter:latest  # <-- ¡Corregido! Sin el ghcr.io/
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Compilar con ESP-IDF y Matter
        run: |
          . /opt/espressif/esp-idf/export.sh
          . /opt/espressif/esp-matter/export.sh
          idf.py set-target esp32
          idf.py build

      - name: Guardar los archivos compilados
        uses: actions/upload-artifact@v4
        with:
          name: Firmware_Listo
          path: |
            build/*.bin
            build/bootloader/*.bin
            build/partition_table/*.bin