name: FIRMWARE SENSOR H2

on: [push] 

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/esp-matter:latest 
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Compilar EXCLUSIVAMENTE para H2
        run: |
          . /opt/espressif/esp-idf/export.sh
          . /opt/espressif/esp-matter/export.sh
          idf.py set-target esp32h2
          idf.py build

      - name: Guardar el Firmware
        uses: actions/upload-artifact@v4
        with:
          name: Firmware_Sensor_H2
          path: |
            build/*.bin
            build/bootloader/*.bin
            build/partition_table/*.bin